sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules
env:
  - DISPLAY=:99.0

before_install:
  - "npm prune"

before_script:
  - "npm ls"

script: "npm run test"

after_success:
  - "npm run cover"
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"

branches:
  only:
    - master
